#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += nt51021_wuxga_dsi_vdo.o lcm_drv_nt51021_wuxga_dsi_vdo.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
