#include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-$(CONFIG_MTK_PMIC)          += pmic_mt6397.o pmic_auxadc.o pmic_chr_type_det.o
obj-$(CONFIG_MTK_BATTERY_PROTECT)  += pmic_battery_protect.o
