#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += cm_n070ice_dsi_vdo_mt8173.o lcm_drv_cm_n070ice_dsi_vdo_mt8173.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
